sudo: required

language: java

jdk:
  - oraclejdk8

env:
  global:
    - IMAGE=jangrott/from_github_to_docker_cloud

services:
  - docker

before_script:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -t $IMAGE:stage .

script:
  - gradle check
  - docker run -d -p 8090:8090 $IMAGE:stage
  - docker ps | grep -q $IMAGE:stage
  - if [ "$TRAVIS_BRANCH" == "master" ]; then docker push $IMAGE:stage; fi
  - if [ "$TRAVIS_BRANCH" == "master" ]; sleep 120; fi
  - if [ "$TRAVIS_BRANCH" == "master" ]; gradle acceptanceTest -Denv.host=fromgithubtodockercloud-stage.d2ac239b.svc.dockerapp.io -Denv.port=8094; fi

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then docker tag $IMAGE:stage $IMAGE:latest; fi
  - if [ "$TRAVIS_BRANCH" == "master" ]; then docker push $IMAGE:latest; fi